version: '3.9'
services:
  nodejs:
    image: node:latest
    restart: always
    deploy:
      replicas: 1
    ports:
      - "8888:8888"
    working_dir: /app
    entrypoint: sh -c "rm -rf gfapi-website && git clone https://github.com/kejonaMC/gfapi-website.git && cp .env /gfapi-website/.env && cd gfapi-website && npm install && npm run build && npm start"
