version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    ports:
      - "80:8888"
    volumes:
      - .:/home/node/
      - node_modules:/home/node/node_modules
    networks:
      - app-network
    command: sh -c "cd /home/fapi-website && node app.js"
