version: '3.9'
services:
  nodejs:
    image: node:latest
    env_file:
      - stack.env
    restart: always
    deploy:
      replicas: 1
    ports:
      - "8888:8888"
    working_dir: /app/gfapi-website
    command: sh -c "cd gfapi-website && npm install && npm run build && npm start"
