version: '3.9'
services:
  nodejs:
    image: node:latest
    env_file:
      - stack.env
    restart: always
    deploy:
      replicas: 1
    ports:
      - "8888:8888"
    environment:
      NODE_ENV: production
    command: npm start
