version: '3.9'
services:
  nodejs:
    image: node:latest
    env_file:
      - stack.env
    restart: always
    deploy:
      replicas: 1
    ports:
      - "8888:8888"
    working_dir: /app
    entrypoint: sh -c "rsync -av --exclude 'logs/' --exclude 'count.json' --delete gfapi-website/ gfapi-website-temp/ && mv gfapi-website-temp/ gfapi-website/ && cd gfapi-website && npm install && npm run build && npm start"
