version: '3.4'

services:
  xuidapi:
    image: xuidapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8888:8888
    volumes:
      - ./app:/app