version: '3.9'
services:
  nodejs:
    image: node:latest
    deploy:
      replicas: 1
    ports:
      - "8000:9999"
    working_dir: /app
    entrypoint: sh -c "git clone https://github.com/kejonaMC/gfapi-website.git && cd gfapi-website && npm install && npm run build && npm start"
    command: sh -c "sleep 5 && rm -rf gfapi-website || true && echo 'gfapi-website removed successfully!' || echo 'gfapi-website removal failed!'"
