version: '3.4'

services:
  mcprofile:
    image: mcprofile
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8888:8888
    command: ["node", "--inspect=0.0.0.0:9229", "app.js"]
